### ISSUE TITLE
Project suggestions?

### ISSUE THREAD

**Issue by mbg** [fpclass/perpetual-haskelling-initiative#1]
We will use this issue to discuss and decide on what the project we are all going to work on is going to be. If you have any ideas or suggestions, please reply below!

Some initial ideas/thoughts:

* A multiplayer game, maybe a [MUD](https://en.wikipedia.org/wiki/MUD) - thanks to @dixonary for the suggestion 
* A tool to teach a particular concept related to functional programming (e.g. how type inference works)
* A smart, configurable Slack/Discord bot for modules which can automatically answer certain  questions about a given module / topic

**Comment by MJHamar** [comment]
Hi!
I have been thinking about summer projects lately and ended up thinking about peer-to-peer based communication. 
I do not know if this topic is applicable in Haskell, but I would be interested in making a simple, peer-to-peer chat application.

**Comment by mbg** [comment]
Peer-to-peer stuff is definitely possible in Haskell (as is anything that can be done in other languages) so we could make something along those lines or something that has a peer-to-peer chat component as part of it.
